name: test

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    name: test
    strategy:
      matrix:
        go: [1.16, 1.17, 1.18]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: install Go
      uses: actions/setup-go@master
      with:
        go-version: ${{ matrix.go }}

    - name: checkout code
      uses: actions/checkout@master

    - name: test
      run: go test ./... -v -cover

  integration-test:
    name: integration test
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: install Go
      uses: actions/setup-go@master
      with:
        go-version: 1.18.x

    - name: checkout code
      uses: actions/checkout@master

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

    - name: test
      run: go test -tags=integration -v

